version = "1.0"

[metadata]
difficulty = "medium"
category = "behavior-change"
tags = [ "javascript", "backend", "websocket",]

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
